# Generated by Django 5.2.1 on 2025-06-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vflox', '0002_alter_lesson_options_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Student',
            new_name='student',
        ),
    ]
