# Generated by Django 5.2.1 on 2025-06-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflox', '0003_rename_student_enrollment_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vflox.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vflox.student')),
            ],
        ),
    ]
